name: build and upload
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: rm package-lock.json yarn.lock
      - run: yarn install
      - uses: actions/cache@v2
        id: turtle-cache
        with:
          path: ~/.turtle
          key: ${{ runner.os }}-turtle
      - name: build
        id: build-expo
        uses: nzws/turtle-action@master
        with:
          build-os: 'android'
          expo-sdk-version: '42.0.0'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ${{ steps.build-expo.outputs.asset-path }}
      - name: upload release
        uses: ncipollo/release-action@v1.8.10
        with:
          prerelease: 'true'
          commit: ${SHA::7}
          artifacts: ${{ steps.build-expo.outputs.asset-path }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          SHA: ${{ github.sha }}